// <auto-generated />
using System;
using BizBook.Products.Api.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizBook.Products.Api.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizBook.Products.Api.Models.Entities.ProductCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProductGroupId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasName("IX_CreatedBy");

                    b.HasIndex("CreatedFrom")
                        .HasName("IX_CreatedFrom");

                    b.HasIndex("Name")
                        .HasName("IX_Name");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("ShopId")
                        .HasName("IX_ShopId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("BizBook.Products.Api.Models.Entities.ProductDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<double>("CostPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<double>("DealerCashPrice")
                        .HasColumnType("float");

                    b.Property<double>("DealerDuePrice")
                        .HasColumnType("float");

                    b.Property<double>("DealerPrice")
                        .HasColumnType("float");

                    b.Property<double>("FranchisePrice")
                        .HasColumnType("float");

                    b.Property<bool>("HasUniqueSerial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRawProduct")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumStockToNotify")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<double>("OnHand")
                        .HasColumnType("float");

                    b.Property<double>("PartnershipPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductCategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<double>("Purchased")
                        .HasColumnType("float");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<double>("Sold")
                        .HasColumnType("float");

                    b.Property<int>("StartingInventory")
                        .HasColumnType("int");

                    b.Property<string>("UniqueSerial")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("BarCode")
                        .HasName("IX_BarCode");

                    b.HasIndex("Brand")
                        .HasName("IX_Brand");

                    b.HasIndex("CreatedBy")
                        .HasName("IX_CreatedBy");

                    b.HasIndex("CreatedFrom")
                        .HasName("IX_CreatedFrom");

                    b.HasIndex("Name")
                        .HasName("IX_Name");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductCode")
                        .HasName("IX_ProductCode");

                    b.HasIndex("ShopId")
                        .HasName("IX_ShopId");

                    b.HasIndex("UniqueSerial")
                        .HasName("IX_UniqueSerial");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("BizBook.Products.Api.Models.Entities.ProductGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CreatedFrom")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasName("IX_CreatedBy");

                    b.HasIndex("CreatedFrom")
                        .HasName("IX_CreatedFrom");

                    b.HasIndex("Name")
                        .HasName("IX_Name");

                    b.HasIndex("ShopId")
                        .HasName("IX_ShopId");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("BizBook.Products.Api.Models.Entities.ProductCategory", b =>
                {
                    b.HasOne("BizBook.Products.Api.Models.Entities.ProductGroup", "ProductGroup")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BizBook.Products.Api.Models.Entities.ProductDetail", b =>
                {
                    b.HasOne("BizBook.Products.Api.Models.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
